# -----Constants-----
DIGIT_DATUM_WIDTH = 28
DIGIT_DATUM_HEIGHT = 28

FACE_DATUM_WIDTH = 60
FACE_DATUM_HEIGHT = 70

DIGITS_TRAINING_DATA_SIZE = 5000
DIGITS_TEST_DATA_SIZE = 1000

FACE_TRAINING_DATA_SIZE = 451
FACE_TEST_DATA_SIZE = 150